spring:
  cloud:
    config:
      server:
        git:
#          uri:  "https://github.com/chudyni/spring-cloud-config-data"
          uri:  "https://github.com/chudyni/spring-cloud-eureka-config-data"
server:
  port: 8001